<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-09 at 08:05:50.
 */
class calculatorTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var calculator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new calculator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * Generated from @assert (0, 0) == 0.
     *
     * @covers calculator::add
     */
    public function testAdd()
    {
        $this->assertEquals(
            0, $this->object->add(0, 0)
        );
    }

    /**
     * Generated from @assert (0, 1) == 1.
     *
     * @covers calculator::add
     */
    public function testAdd2()
    {
        $this->assertEquals(
            1, $this->object->add(0, 1)
        );
    }

    /**
     * Generated from @assert (1, 0) == 1.
     *
     * @covers calculator::add
     */
    public function testAdd3()
    {
        $this->assertEquals(
            1, $this->object->add(1, 0)
        );
    }

    /**
     * Generated from @assert (1, 1) == 2.
     *
     * @covers calculator::add
     */
    public function testAdd4()
    {
        $this->assertEquals(
            2, $this->object->add(1, 1)
        );
    }

    /**
     * Generated from @assert (1, 2) == 4.
     *
     * @covers calculator::add
     */
    public function testAdd5()
    {
        $this->assertEquals(
            4, $this->object->add(1, 2)
        );
    }
}